---
- name: downloading the terraform binary
  get_url:
    url: https://releases.hashicorp.com/terraform/1.2.1/terraform_1.2.1_linux_arm64.zip
    dest: /tmp/terraform.zip

- name: unzipping the terraform binary
  unarchive:
    src: /tmp/terraform.zip
    dest: /usr/local/bin/
    remote_src: yes
