---
- name: downloading the terraform binary
  get_url:
    url: '{{ terraform_url }}'
    dest: /tmp/terraform.zip

- name: unzipping the terraform binary
  unarchive:
    src: /tmp/terraform.zip
    dest: /usr/local/bin/
    remote_src: yes
