---
- name: installing aptitude
  apt:
    name: aptitude
    state: latest
    update_cache: true

- name: installing packages
  apt:
    name: '{{ item }}'
    state: present
    update_cache: yes
  with_items:
    - '{{ linux_packages_to_install }}'
