---
- name: populating service facts
  service_facts:

- name: getting docker service status
  set_fact:
    docker_installed: yes
  when: "'docker' in services"

- name: installing docker
  block:
    - name: getting install docker script
      get_url:
        url: https://get.docker.com
        dest: /tmp/get-docker.sh

    - name: installing docker
      shell: /tmp/get-docker.sh > /var/log/get-docker.log
  when: not docker_installed | bool
